import Link from 'next/link';
import { Inter } from 'next/font/google';
import './globals.css'

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {

  return (
    <html lang='en'>
      <body className={inter.className}>
        <header>
          <nav>
            <ul className='navbar__list'>
              <li className='navbar__list-item'><Link className='navbar__list-item-link' href='/'>Home</Link></li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
