import Link from 'next/link';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {

  return (
    <html lang='en'>
      <body className={inter.className}>
        <header>
          <nav>
            <ul>
              <li><Link href='/'>Home</Link></li>
              <li><Link href='/post'>Post</Link></li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
